package com.tesco.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T21:03:12.424+05:30
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "CitiBankServiceImplProviderService", 
                  wsdlLocation = "file:/D:/Eclipse_WorkspaceWebservices_Lara/FirstClientProject/WebContent/citibankserviceimplprovider.wsdl",
                  targetNamespace = "http://impl.service.tesco.com/") 
public class CitiBankServiceImplProviderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.tesco.com/", "CitiBankServiceImplProviderService");
    public final static QName CitiBankServiceImplProviderPort = new QName("http://impl.service.tesco.com/", "CitiBankServiceImplProviderPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Eclipse_WorkspaceWebservices_Lara/FirstClientProject/WebContent/citibankserviceimplprovider.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CitiBankServiceImplProviderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Eclipse_WorkspaceWebservices_Lara/FirstClientProject/WebContent/citibankserviceimplprovider.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CitiBankServiceImplProviderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CitiBankServiceImplProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CitiBankServiceImplProviderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CitiBankServiceImplProviderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CitiBankServiceImplProviderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CitiBankServiceImplProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CitiBankServiceImplProvider
     */
    @WebEndpoint(name = "CitiBankServiceImplProviderPort")
    public CitiBankServiceImplProvider getCitiBankServiceImplProviderPort() {
        return super.getPort(CitiBankServiceImplProviderPort, CitiBankServiceImplProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CitiBankServiceImplProvider
     */
    @WebEndpoint(name = "CitiBankServiceImplProviderPort")
    public CitiBankServiceImplProvider getCitiBankServiceImplProviderPort(WebServiceFeature... features) {
        return super.getPort(CitiBankServiceImplProviderPort, CitiBankServiceImplProvider.class, features);
    }

}
