package com.tesco.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T21:03:12.412+05:30
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://impl.service.tesco.com/", name = "CitiBankServiceImplProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface CitiBankServiceImplProvider {

    @WebMethod(action = "urn:ValidateCriditCard")
    @RequestWrapper(localName = "validateCriditCard", targetNamespace = "http://impl.service.tesco.com/", className = "com.tesco.client.ValidateCriditCard")
    @ResponseWrapper(localName = "validateCriditCardResponse", targetNamespace = "http://impl.service.tesco.com/", className = "com.tesco.client.ValidateCriditCardResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean validateCriditCard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
