
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.tesco.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-30T21:03:12.345+05:30
 * Generated source version: 3.1.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CitiBankServiceImplProviderService",
                      portName = "CitiBankServiceImplProviderPort",
                      targetNamespace = "http://impl.service.tesco.com/",
                      wsdlLocation = "file:/D:/Eclipse_WorkspaceWebservices_Lara/FirstClientProject/WebContent/citibankserviceimplprovider.wsdl",
                      endpointInterface = "com.tesco.client.CitiBankServiceImplProvider")
                      
public class CitiBankServiceImplProviderPortImpl implements CitiBankServiceImplProvider {

    private static final Logger LOG = Logger.getLogger(CitiBankServiceImplProviderPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.tesco.client.CitiBankServiceImplProvider#validateCriditCard(java.lang.Integer  arg0 )*
     */
    public java.lang.Boolean validateCriditCard(java.lang.Integer arg0) { 
        LOG.info("Executing operation validateCriditCard");
        System.out.println(arg0);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
