
package com.tesco.service.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.2
 * Sun Aug 30 12:53:44 IST 2015
 * Generated source version: 3.1.2
 */

@XmlRootElement(name = "validateCriditCardResponse", namespace = "http://impl.service.tesco.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateCriditCardResponse", namespace = "http://impl.service.tesco.com/")

public class ValidateCriditCardResponse {

    @XmlElement(name = "return")
    private java.lang.Boolean _return;

    public java.lang.Boolean getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.Boolean new_return)  {
        this._return = new_return;
    }

}

